apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: resume-generator
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/resume-generator
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
