echo "🚀 Quick Start Commands:"
echo ""
echo "# 1. Install Firebase CLI (if not installed)"
echo "npm install -g firebase-tools"
echo ""
echo "# 2. Login to Firebase"
echo "firebase login"
echo ""
echo "# 3. Run setup script"
echo "chmod +x setup-firebase.sh"
echo "./setup-firebase.sh"
echo ""
echo "# 4. Start development"
echo "firebase emulators:start  # Terminal 1 - Firebase Functions"
echo "npm start                 # Terminal 2 - React App"
echo ""
echo "# 5. Deploy to production"
echo "./deploy-firebase.sh"
